# Generated by Django 3.1.7 on 2021-03-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Russian'), ('en', 'English')], default='ru', help_text='Language of a book', max_length=2),
        ),
    ]
